### ISSUE TITLE
Define rules by tagname without implementation attribute

### ISSUE THREAD

**Issue by masooh** [1and1/ono-extra-enforcer-rules#2]
This works for the standard rules, but is not described in http://maven.apache.org/enforcer/enforcer-api/writing-a-custom-rule.html how to do that.

**Comment by masooh** [comment]
This will possibly not be possible as `implementation` attribute can only be ommited if object is in the same package as the Mojo. In this case: `org.apache.maven.plugins.enforcer`. See: https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Mapping_Complex_Objects

**Comment by leonard84** [comment]
You could add adapter classes in the `org.apache.maven.plugins.enforcer` package, that have the same name as the rules and simply extend them.
